INSERT INTO skills (skill_name, tag) VALUES
('APACHE GROOVY', 'Languages'),
('ASSEMBLY SCRIPT', 'Languages'),
('C', 'Languages'),
('C#', 'Languages'),
('C++', 'Languages'),
('CLOJURE', 'Languages'),
('CRYSTAL', 'Languages'),
('CSS3', 'Languages'),
('DART', 'Languages'),
('DGRAPH', 'Languages'),
('ELIXIR', 'Languages'),
('ELM', 'Languages'),
('ERLANG', 'Languages'),
('FORTRAN', 'Languages'),
('GO/GOLANG', 'Languages'),
('GRAPHQL', 'Languages'),
('HASKELL', 'Languages'),
('HTML5', 'Languages'),
('JAVA', 'Languages'),
('JAVASCRIPT', 'Languages'),
('JULIA', 'Languages'),
('KOTLIN', 'Languages'),
('LATEX', 'Languages'),
('LUA', 'Languages'),
('MARKDOWN', 'Languages'),
('NIM', 'Languages'),
('NIX', 'Languages'),
('OBJECTIVE-C', 'Languages'),
('OCAML', 'Languages'),
('OCTAVE', 'Languages'),
('ORG MODE', 'Languages'),
('PERL', 'Languages'),
('PHP', 'Languages'),
('POWERSHELL', 'Languages'),
('PYTHON', 'Languages'),
('R', 'Languages'),
('RESCRIPT', 'Languages'),
('RUBY', 'Languages'),
('RUST', 'Languages'),
('SCALA', 'Languages'),
('BASH SCRIPT', 'Languages'),
('SOLIDITY', 'Languages'),
('SWIFT', 'Languages'),
('TYPESCRIPT', 'Languages'),
('WINDOWS TERMINAL', 'Languages'),
('ZIG', 'Languages');




INSERT INTO skills (skill_name, tag) VALUES
('ALIBABA CLOUD', 'Hosting / Saas'),
('AWS', 'Hosting / Saas'),
('AZURE', 'Hosting / Saas'),
('CLOUDFLARE', 'Hosting / Saas'),
('CODEBERG', 'Hosting / Saas'),
('DATADOG', 'Hosting / Saas'),
('DIGITALOCEAN', 'Hosting / Saas'),
('FIREBASE', 'Hosting / Saas'),
('GLITCH', 'Hosting / Saas'),
('GOOGLE CLOUD', 'Hosting / Saas'),
('HEROKU', 'Hosting / Saas'),
('LINODE', 'Hosting / Saas'),
('NETLIFY', 'Hosting / Saas'),
('ORACLE', 'Hosting / Saas'),
('OPENSTACK', 'Hosting / Saas'),
('OVH', 'Hosting / Saas'),
('RENDER', 'Hosting / Saas'),
('SCALEWAY', 'Hosting / Saas'),
('VERCEL', 'Hosting / Saas'),
('VULTR', 'Hosting / Saas');

INSERT INTO skills (skill_name, tag) VALUES
('.NET', 'Framework Platforms & Libraries'),
('ADONISJS', 'Framework Platforms & Libraries'),
('ALPINE.JS', 'Framework Platforms & Libraries'),
('ANACONDA', 'Framework Platforms & Libraries'),
('ANGULAR', 'Framework Platforms & Libraries'),
('ANGULARJS', 'Framework Platforms & Libraries'),
('ANT DESIGN', 'Framework Platforms & Libraries'),
('APACHE SPARK', 'Framework Platforms & Libraries'),
('APACHE KAFKA', 'Framework Platforms & Libraries'),
('APACHE HADOOP', 'Framework Platforms & Libraries'),
('APACHE HIVE', 'Framework Platforms & Libraries'),
('APOLLO GRAPHQL', 'Framework Platforms & Libraries'),
('ASTRO', 'Framework Platforms & Libraries'),
('AURELIA', 'Framework Platforms & Libraries'),
('BLAZOR', 'Framework Platforms & Libraries'),
('BOOTSTRAP', 'Framework Platforms & Libraries'),
('BUEFY', 'Framework Platforms & Libraries'),
('BULMA', 'Framework Platforms & Libraries'),
('BUN', 'Framework Platforms & Libraries'),
('CHAKRA UI', 'Framework Platforms & Libraries'),
('CHART.JS', 'Framework Platforms & Libraries'),
('CODE IGNITER', 'Framework Platforms & Libraries'),
('CONTEXT API', 'Framework Platforms & Libraries'),
('CUDA', 'Framework Platforms & Libraries'),
('DAISYUI', 'Framework Platforms & Libraries'),
('DENO JS', 'Framework Platforms & Libraries'),
('DIRECTUS', 'Framework Platforms & Libraries'),
('DJANGO', 'Framework Platforms & Libraries'),
('DJANGOREST', 'Framework Platforms & Libraries'),
('DRUPAL', 'Framework Platforms & Libraries'),
('EJS', 'Framework Platforms & Libraries'),
('ELASTICSEARCH - Apache Lucene', 'Framework Platforms & Libraries'),
('ELECTRON.JS', 'Framework Platforms & Libraries'),
('EMBER', 'Framework Platforms & Libraries'),
('ESBUILD', 'Framework Platforms & Libraries'),
('EXPO', 'Framework Platforms & Libraries'),
('EXPRESS.JS', 'Framework Platforms & Libraries'),
('FASTAPI', 'Framework Platforms & Libraries'),
('FASTIFY', 'Framework Platforms & Libraries'),
('FILAMENT', 'Framework Platforms & Libraries'),
('FLASK', 'Framework Platforms & Libraries'),
('FLUTTER', 'Framework Platforms & Libraries'),
('FRAMEWORK7', 'Framework Platforms & Libraries'),
('GATSBY.JS', 'Framework Platforms & Libraries'),
('GRAV', 'Framework Platforms & Libraries'),
('GREEN SOCK', 'Framework Platforms & Libraries'),
('GULP', 'Framework Platforms & Libraries'),
('GUTENBERG', 'Framework Platforms & Libraries'),
('INSOMNIA', 'Framework Platforms & Libraries'),
('HANDLEBARS', 'Framework Platforms & Libraries'),
('IONIC', 'Framework Platforms & Libraries'),
('JASMINE', 'Framework Platforms & Libraries'),
('JAVA FX', 'Framework Platforms & Libraries'),
('JINJA', 'Framework Platforms & Libraries'),
('JOOMLA', 'Framework Platforms & Libraries'),
('JQUERY', 'Framework Platforms & Libraries'),
('JWT/JSON WEB TOKEN', 'Framework Platforms & Libraries'),
('LARAVEL', 'Framework Platforms & Libraries'),
('LIVEWIRE', 'Framework Platforms & Libraries'),
('LESS', 'Framework Platforms & Libraries'),
('MUI', 'Framework Platforms & Libraries'),
('METEOR JS', 'Framework Platforms & Libraries'),
('MANTINE', 'Framework Platforms & Libraries'),
('MAXCOMPUTE', 'Framework Platforms & Libraries'),
('NPM', 'Framework Platforms & Libraries'),
('NEST.JS', 'Framework Platforms & Libraries'),
('NEXT JS', 'Framework Platforms & Libraries'),
('NODE.JS', 'Framework Platforms & Libraries'),
('NODEMON', 'Framework Platforms & Libraries'),
('NODE-RED', 'Framework Platforms & Libraries'),
('NUXT.JS', 'Framework Platforms & Libraries'),
('NX', 'Framework Platforms & Libraries'),
('OPENCV', 'Framework Platforms & Libraries'),
('OPENGL LIBRARY', 'Framework Platforms & Libraries'),
('PJS', 'Framework Platforms & Libraries'),
('PHOENIX FRAMEWORK', 'Framework Platforms & Libraries'),
('PNPM', 'Framework Platforms & Libraries'),
('PUG', 'Framework Platforms & Libraries'),
('QT', 'Framework Platforms & Libraries'),
('QUARKUS', 'Framework Platforms & Libraries'),
('QUASAR', 'Framework Platforms & Libraries'),
('ROS', 'Framework Platforms & Libraries'),
('RABBITMQ', 'Framework Platforms & Libraries'),
('RADIX UI', 'Framework Platforms & Libraries'),
('RAILS', 'Framework Platforms & Libraries'),
('RAYLIB', 'Framework Platforms & Libraries'),
('REACT', 'Framework Platforms & Libraries'),
('REACT NATIVE', 'Framework Platforms & Libraries'),
('REACT QUERY', 'Framework Platforms & Libraries'),
('REACT ROUTER', 'Framework Platforms & Libraries'),
('REACT HOOK FORM', 'Framework Platforms & Libraries'),
('REDUX', 'Framework Platforms & Libraries'),
('REMIX', 'Framework Platforms & Libraries'),
('ROLLUP.JS', 'Framework Platforms & Libraries'),
('RXDB', 'Framework Platforms & Libraries'),
('RXJS', 'Framework Platforms & Libraries'),
('SASS', 'Framework Platforms & Libraries'),
('SEMANTIC UI REACT', 'Framework Platforms & Libraries'),
('SNOWFLAKE', 'Framework Platforms & Libraries'),
('SOCKET.IO', 'Framework Platforms & Libraries'),
('SOLID.JS', 'Framework Platforms & Libraries'),
('SPRING', 'Framework Platforms & Libraries'),
('STRAPI', 'Framework Platforms & Libraries'),
('STREAMLIT', 'Framework Platforms & Libraries'),
('STYLED COMPONENTS', 'Framework Platforms & Libraries'),
('STYLUS', 'Framework Platforms & Libraries'),
('SVELTE', 'Framework Platforms & Libraries'),
('SVELTEKIT', 'Framework Platforms & Libraries'),
('SYMFONY', 'Framework Platforms & Libraries'),
('TAILWINDCSS', 'Framework Platforms & Libraries'),
('TAURI', 'Framework Platforms & Libraries'),
('THREE.JS', 'Framework Platforms & Libraries'),
('THYMELEAF', 'Framework Platforms & Libraries'),
('TRPC', 'Framework Platforms & Libraries'),
('TYPEGRAPHQL', 'Framework Platforms & Libraries'),
('UNOCSS', 'Framework Platforms & Libraries'),
('VITE', 'Framework Platforms & Libraries'),
('VUE.JS', 'Framework Platforms & Libraries'),
('VUETIFY', 'Framework Platforms & Libraries'),
('WEBGL', 'Framework Platforms & Libraries'),
('WEBPACK', 'Framework Platforms & Libraries'),
('WEB3.JS', 'Framework Platforms & Libraries'),
('WINDICSS', 'Framework Platforms & Libraries'),
('WORDPRESS', 'Framework Platforms & Libraries'),
('XAMARIN', 'Framework Platforms & Libraries'),
('YARN', 'Framework Platforms & Libraries');



INSERT INTO skills (skill_name, tag) VALUES
('APACHE', 'Servers'),
('APACHE AIRFLOW', 'Servers'),
('APACHE ANT', 'Servers'),
('APACHE FLINK', 'Servers'),
('APACHE MAVEN', 'Servers'),
('APACHE TOMCAT', 'Servers'),
('GUNICORN', 'Servers'),
('JENKINS', 'Servers'),
('NGINX', 'Servers');

INSERT INTO skills (skill_name, tag) VALUES
('AMAZON DYNAMODB', 'Databases/ORM'),
('APPWRITE', 'Databases/ORM'),
('ARANGODB', 'Databases/ORM'),
('CASSANDRA', 'Databases/ORM'),
('COCKROACH LABS', 'Databases/ORM'),
('COUCHBASE', 'Databases/ORM'),
('CRATEDB', 'Databases/ORM'),
('FIREBASE FIRESTORE', 'Databases/ORM'),
('INFLUXDB', 'Databases/ORM'),
('MARIADB', 'Databases/ORM'),
('MUSICBRAINZ', 'Databases/ORM'),
('MICROSOFT SQL SERVER', 'Databases/ORM'),
('MONGODB', 'Databases/ORM'),
('MYSQL', 'Databases/ORM'),
('NEO4J', 'Databases/ORM'),
('PLANETSCALE', 'Databases/ORM'),
('POCKETBASE', 'Databases/ORM'),
('POSTGRES', 'Databases/ORM'),
('REALM', 'Databases/ORM'),
('REDIS', 'Databases/ORM'),
('SINGLE STORE', 'Databases/ORM'),
('SQLITE', 'Databases/ORM'),
('SUPABASE', 'Databases/ORM'),
('SURREALDB', 'Databases/ORM'),
('TERADATA', 'Databases/ORM'),
('HIBERNATE', 'Databases/ORM'),
('PRISMA', 'Databases/ORM'),
('SEQUELIZE', 'Databases/ORM'),
('QUILL', 'Databases/ORM');
INSERT INTO skills (skill_name, tag) VALUES
('ADOBE', 'Design'),
('ADOBE ACROBAT READER', 'Design'),
('ADOBE AFTER EFFECTS', 'Design'),
('ADOBE AUDITION', 'Design'),
('ADOBE CREATIVE CLOUD', 'Design'),
('ADOBE DREAMWEAVER', 'Design'),
('ADOBE FONTS', 'Design'),
('ADOBE ILLUSTRATOR', 'Design'),
('ADOBE INDESIGN', 'Design'),
('ADOBE LIGHTROOM', 'Design'),
('ADOBE LIGHTROOM CLASSIC', 'Design'),
('ADOBE PHOTOSHOP', 'Design'),
('ADOBE PREMIERE PRO', 'Design'),
('ADOBE XD', 'Design'),
('ASEPRITE', 'Design'),
('AFFINITY DESIGNER', 'Design'),
('AFFINITY PHOTO', 'Design'),
('BLENDER', 'Design'),
('CANVA', 'Design'),
('CLIP STUDIO PAINT', 'Design'),
('DRIBBBLE', 'Design'),
('FIGMA', 'Design'),
('FRAMER', 'Design'),
('GIMP', 'Design'),
('INKSCAPE', 'Design'),
('INVISION', 'Design'),
('KRITA', 'Design'),
('PROTO.IO', 'Design'),
('RHINOCEROS', 'Design'),
('SKETCH', 'Design'),
('SKETCH UP', 'Design'),
('STORYBOOK', 'Design');

INSERT INTO skills (skill_name, tag) VALUES
('KERAS', 'ML/DL/AI'),
('MATPLOTLIB', 'ML/DL/AI'),
('MLFLOW', 'ML/DL/AI'),
('NUMPY', 'ML/DL/AI'),
('PANDAS', 'ML/DL/AI'),
('PLOTLY', 'ML/DL/AI'),
('PYTORCH', 'ML/DL/AI'),
('SCIKIT-LEARN', 'ML/DL/AI'),
('SCIPY', 'ML/DL/AI'),
('TENSORFLOW', 'ML/DL/AI');

INSERT INTO skills (skill_name, tag) VALUES
('CIRCLECI', 'CI/CD VCS'),
('CHIPPERCI', 'CI/CD VCS'),
('CLOUDBEES', 'CI/CD VCS'),
('FASTLANE', 'CI/CD VCS'),
('GITLAB CI', 'CI/CD VCS'),
('GITHUB ACTIONS', 'CI/CD VCS'),
('TEAMCITY', 'CI/CD VCS'),
('TRAVIS CI', 'CI/CD VCS'),
('OCTOPUS DEPLOY', 'CI/CD VCS'),
('APACHE SUBVERSION', 'CI/CD VCS'),
('BITBUCKET', 'CI/CD VCS'),
('FORGEJO', 'CI/CD VCS'),
('GIT', 'CI/CD VCS'),
('GITEA', 'CI/CD VCS'),
('GITEE', 'CI/CD VCS'),
('GITHUB', 'CI/CD VCS'),
('GITLAB', 'CI/CD VCS'),
('GITPOD', 'CI/CD VCS'),
('MERCURIAL', 'CI/CD VCS'),
('PERFORCE HELIX', 'CI/CD VCS');


INSERT INTO skills (skill_name, tag) VALUES
('AIRBNB', 'Other'),
('ALFRED', 'Other'),
('ANSIBLE', 'Other'),
('AQUA SEC', 'Other'),
('ARDUINO', 'Other'),
('BABEL', 'Other'),
('BITWARDEN', 'Other'),
('CISCO', 'Other'),
('CMAKE', 'Other'),
('CODECOV', 'Other'),
('CONFLUENCE', 'Other'),
('CROWDIN', 'Other'),
('DOCKER', 'Other'),
('ESLINT', 'Other'),
('ELASTICSEARCH ', 'Other'),
('FFMPEG', 'Other'),
('GRADLE', 'Other'),
('GRAFANA', 'Other'),
('HOME ASSISTANT', 'Other'),
('HOMEBRIDGE', 'Other'),
('JELLYFIN', 'Other'),
('JIRA', 'Other'),
('KUBERNETES', 'Other'),
('META', 'Other'),
('MOSQUITTO', 'Other'),
('NOTION', 'Other'),
('OPENAPI SPECIFICATION', 'Other'),
('OPENSEA', 'Other'),
('OPENTELEMETRY', 'Other'),
('PACKER', 'Other'),
('PI-HOLE', 'Other'),
('PLATFORMIO', 'Other'),
('PLEX', 'Other'),
('PORTFOLIO', 'Other'),
('POSTMAN', 'Other'),
('POWER BI', 'Other'),
('PRETTIER', 'Other'),
('PREZI', 'Other'),
('PROMETHEUS', 'Other'),
('RANCHER', 'Other'),
('RASPBERRY PI', 'Other'),
('SONARLINT', 'Other'),
('SONARQUBE', 'Other'),
('SPLUNK', 'Other'),
('SWAGGER', 'Other'),
('TAMPERMONKEY', 'Other'),
('TOR', 'Other'),
('TERRAFORM', 'Other'),
('TRELLO', 'Other'),
('TWILIO', 'Other'),
('UBER', 'Other'),
('UBIQUITI', 'Other'),
('VAGRANT', 'Other'),
('WIREGUARD', 'Other'),
('XFCE', 'Other'),
('ZIGBEE', 'Other'),
('AMD', 'Other'),
('ANALOGUE', 'Other'),
('BATTLE.NET', 'Other'),
('BEVY', 'Other'),
('EA', 'Other'),
('EPIC GAMES', 'Other'),
('GODOT ENGINE', 'Other'),
('HUMBLE BUNDLE', 'Other'),
('ITCH.IO', 'Other'),
('NVIDIA', 'Other'),
('OPENGL', 'Other'),
('PLAYSTATION NETWORK', 'Other'),
('RIOT GAMES', 'Other'),
('SIDEQUEST', 'Other'),
('SQUARE ENIX', 'Other'),
('STEAM', 'Other'),
('UBISOFT', 'Other'),
('UNITY', 'Other'),
('UNREAL ENGINE', 'Other'),
('XBOX', 'Other');